Repository algo-itzy/cs-itzy, pull requests merged in 2021-11, with the labels that each got.

#14 [Data Structure] Array 211004 (seokzin)
  data_structure/Array.md
Labels: 🌰 소석진

#15 [Data Structure] Hash 211004 (Seungjoo)
  data_structure/Hash.assets/image-20211104163140246.png
  data_structure/Hash.assets/image-20211104163232799.png
  data_structure/Hash.assets/image-20211104163251612.png
  data_structure/Hash.md
Labels: 😀 한승주

#16 [Data Structure] Tree 211104 (jiwoong)
  data_structure/Tree.md
Labels: 😀 정지웅

#18 [Data Structure] Linked List 211104 (yeonhee)
  data_structure/Linked_list.md
Labels: 🔮 채연희

#17 [Data Structure] Heap 211104 (seungkyu)
  data_structure/Heap.md
Labels: :monkey_face: 김승규

#19 [Data Structure] Stack 211104 (yoonbaek)
  data_structure/Stack.md
Labels: 😀 백승윤

#22 docs: Network 211114 (seungjoo)
  data_structure/Hash.md
  network/TCPUDP.md
Labels: 😀 한승주

#20 docs: Network 211114 (seokzin)
  network/HTTP-HTTPS.md
Labels: 🌰 소석진

#25 docs: Network 211114 (seungkyu)
  network/OSI 7계층.md
Labels: :monkey_face: 김승규

#24 docs: Network 211114 (yeonhee)
  network/RESTful_API.md
Labels: 🔮 채연희

#23 docs: Network 211114 (yoonbaek)
  network/WebServer_WAS_Proxy.md
Labels: 😀 백승윤
