Repository algo-itzy/cs-itzy, pull requests merged in 2021-12, with the labels that each got.

#26 docs: Operating System 211202 (seokzin)
  operating_system/가상_메모리.md
Labels: 🌰 소석진

#27 docs: Operating System 211202 (yeonhee)
  operating_system/Process_Synchronization.md
Labels: 🔮 채연희

#28 docs: Operating System 211202 (seungkyu)
  operating_system/File System, Disk Management.md
Labels: :monkey_face: 김승규

#36 docs: Upsate Operating System 211202 (seungjoo)
  operating_system/메모리관리.assets/image-20211205075017276.png
  operating_system/메모리관리.assets/image-20211205083445835.png
  operating_system/메모리관리.assets/image-20211205083713524.png
  operating_system/메모리관리.assets/image-20211205084954023.png
  operating_system/메모리관리.assets/image-20211205090302403.png
  operating_system/메모리관리.assets/image-20211205091100068.png
  operating_system/메모리관리.assets/image-20211205091211698.png
  operating_system/메모리관리.assets/image-20211205091423658.png
  operating_system/메모리관리.assets/image-20211205091934085.png
  operating_system/메모리관리.assets/image-20211205095828390.png
  operating_system/메모리관리.assets/image-20211205100045021.png
  operating_system/메모리관리.assets/image-20211205100725159.png
  operating_system/메모리관리.assets/image-20211205101839019.png
  operating_system/메모리관리.assets/image-20211205101849522.png
  operating_system/메모리관리.assets/image-20211205102745718.png
  operating_system/메모리관리.assets/image-20211205102831958.png
  operating_system/메모리관리.assets/image-20211205104755529.png
  operating_system/메모리관리.assets/image-20211205105629670.png
  operating_system/메모리관리.assets/image-20211205110948577.png
  operating_system/메모리관리.assets/image-20211205112108094.png
  operating_system/메모리관리.assets/image-20211205112701631.png
  operating_system/메모리관리.assets/image-20211205113438225.png
  operating_system/메모리관리.assets/image-20211205113838194.png
  operating_system/메모리관리.assets/image-20211205113945646.png
  operating_system/메모리관리.md
Labels: 😀 한승주
